apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: import-definitions
spec:
  replicas: 1
  override:
    statefulSet:
      spec:
        template:
          spec:
            containers:
            - name: rabbitmq
              volumeMounts:
              - mountPath: /etc/rabbitmq/definitions.json
                subPath: definitions.json # Name of the ConfigMap field containing definitions
                name: definitions
            volumes:
            - name: definitions
              configMap:
                name: definitions # Name of the ConfigMap which contains definitions you wish to import
  rabbitmq:
    additionalPlugins:
      - rabbitmq_shovel
    additionalConfig: |
      channel_max = 200
      default_user = guest
      default_pass = guest
      disk_free_limit.relative = 1.5
      management.path_prefix = /rabbitmq
      vm_memory_high_watermark.relative = 0.7
      vm_memory_high_watermark_paging_ratio = 0.9
      load_definitions = /etc/rabbitmq/definitions.json # Path to the mounted definitions file
