# kind: PersistentVolume
# apiVersion: v1
# metadata:
#   name: postgres-pv-volume  # Sets PV's name
#   labels: 
#     app: postgres
# spec:
#   storageClassName: ""
#   capacity:
#     storage: 5Gi # Sets PV Volume
#   accessModes:
#     - ReadWriteMany
#   gcePersistentDisk:
#     fsType: ext4
# ---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-claim  # Sets name of PVC
  labels:
    app: postgres
spec:
  storageClassName: "standard-rwo"
  accessModes:
    - ReadWriteOnce  # Sets read and write access
  resources:
    requests:
      storage: 5Gi  # Sets volume size
