kind: Deployment
apiVersion: apps/v1
metadata:
  name: traefik-deployment
  labels:
    app: traefik

spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      serviceAccountName: traefik-account
      containers:
        - name: traefik
          image: traefik:v2.10
          args:
            - --api.insecure
            - --providers.kubernetesingress
            - --providers.kubernetesCRD
            - --entryPoints.http.address=:80
            - --entryPoints.tcpep.address=:8085
            - --accesslog
            - --accesslog.format=json
            - --accesslog.filepath=/data/access.log
          ports:
            - name: web
              containerPort: 80
            - name: dashboard
              containerPort: 8080
            - name: tcp
              containerPort: 8200
          volumeMounts:
            - mountPath: /data/log
              name: logdir
      volumes:
      - name: logdir
        emptyDir: {}
