---
apiVersion: v1
kind: Namespace
metadata:
  name: "${ns}"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluent-bit
  namespace: "${ns}"
  annotations:
    eks.amazonaws.com/role-arn: "${IAM_ROLE}"
